### ISSUE TITLE
grpc service error when generate

### ISSUE THREAD

**Issue by kaybinwong** [protostuff/protostuff-compiler#41]
when i generate code from proto file with grpc service, it got error. does it not support grpc service yet?
**proto file**
`service PBBasicService {
    rpc callApi(PBMessageRequest) returns(PBMessageResponse);
}`
**logs**
[ERROR] Caused by: org.stringtemplate.v4.misc.STNoSuchPropertyException: no such property: io.protostuff.compiler.model.ServiceMethod.javaReturnTypeFullName

**Comment by kshchepanovskyi** [comment]
No, there is no compatibility between grpc and protostuff.
You should use native `protoc` for generating classes compatible with grpc.
