### ISSUE TITLE
Map fields

### ISSUE THREAD

**Issue by bagrusss** [protostuff/protostuff-compiler#50]
I have message with **map** field:
message PairsMsg {
...
    map<string, string> pairs = 1;
...
}
and got this error
ERROR i.p.c.c.ProtostuffCompilerCli - Unknown option: 'map_entry' [unknown]

**Comment by kshchepanovskyi** [comment]
Are you using custom `google/protobuf/descriptor.proto`?

**Comment by kshchepanovskyi** [comment]
This option comes from here: https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto#L451

**Comment by bagrusss** [comment]
No I have not this option.

**Comment by bagrusss** [comment]
Is there any progress on this issue? 
When about wait for the support of the map fields?

**Comment by kshchepanovskyi** [comment]
Map fields are fully supported and covered by tests: 

- https://github.com/protostuff/protostuff-compiler/blob/master/protostuff-it/src/test/proto/io/protostuff/it/message.proto#L21
- https://github.com/protostuff/protostuff-compiler/blob/master/protostuff-it/src/test/java/io/protostuff/it/java/MessageTest.java

Please create some minimal project that reproduces an issue, then I will be able to help.

**Comment by bagrusss** [comment]
I use custom descriptor.proto, but without map_entry option.
Here is an [example](https://gist.github.com/bagrusss/7a47adb75d9b405af764bcae08bce310), when protostuff compiler fails with `ERROR i.p.c.c.ProtostuffCompilerCli - Unknown option: 'map_entry' [unknown]`

Removing `optional string experimental_map_key = 9;` provides nothing.

**Comment by kshchepanovskyi** [comment]
You must upgrade your `descriptor.proto` to the new one, which contains `map_entry` option.
You can take it from https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto

Your version of this file is old, it comes from `protoc` version that did not support maps.
