### ISSUE TITLE
Running the Compiler from Gradle (Not a real issue)

### ISSUE THREAD

**Issue by MonsterOfCookie** [protostuff/protostuff-compiler#53]
Hey, 

I just wanted share how to run the compiler from Gradle if you wanted to add it to the wiki for others who might come looking.

Essentially in your Gradle build file you can specify a configuration like so

```groovy
configurations {
    protoCompile
}
```

Then add the CLI dependency using that configuration.

```groovy
dependencies {
    protoCompile "io.protostuff:protostuff-cli:0-SNAPSHOT"
}
```

Then to run it, just create task and do the following.

```groovy
task generateSource() {
    ant.java(classname: 'io.protostuff.compiler.cli.ProtostuffCompilerCli', fork: 'true', failOnError: 'true') {
        arg(value: 'MyProto.proto')
        arg(value: '-g=java')
        arg(value: '-I=' + project.projectDir.path + "/../proto/")
        arg(value: '-o=' + project.buildDir.path + "/generated/")
        classpath {
            pathElement(path: configurations.protoCompile.asPath)
        }
    }
}
```

Then on call the task, I have it as part of the build so on "clean" the generated files are deleted and on build they are re-generated.

`/gradlew generateSource`

**Comment by kshchepanovskyi** [comment]
Thanks, I'll add it to readme.

**Comment by kshchepanovskyi** [comment]
https://github.com/protostuff/protostuff-compiler/wiki/Gradle
