### ISSUE TITLE
Generator Extensions

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protostuff-compiler#8]
Design extensible template system that enables code generation for any language.

**Comment by PaniniGelato** [comment]
I extended ProtostuffCompiler to inject my custom compilerModule for cpp generator
```
    public MyProtostuffCompiler(String customModule) {
        injector = Guice.createInjector(
                new ParserModule(), Class.forName(customModule).newInstance());
    }
```

**Comment by kshchepanovskyi** [comment]
@PaniniGelato can you please share more details how are you generating cpp code? Like, are you using maven/ant/gradle/other build system or CLI, what template engine, etc. Mayble we can simplify your customizations.

I am working on an extension for java generator for maven, and it is based on StringTemplate.
Idea is to make entry point to StringTemplate configurble, so that [we can override particular templates](https://github.com/antlr/stringtemplate4/blob/master/doc/inheritance.md).

**Sample:**

Maven config:

```xml
<configuration>
    <template>${project.basedir}/src/main/stg/io/protostuff/it/extension.stg</template>
</configuration>
```

`extension.stg`:

```
import "io/protostuff/generator/java/main.stg"

rpc_return_type(method) ::= <%
java.util.concurrent.CompletableFuture\<<method.returnType.javaFullName>>
%>
```

This is very basic example, but in similar way it is possible to implement the whole generator.

**Comment by PaniniGelato** [comment]
@kshchepanovskyi My project use Maven, depends on protostuff-generator v2.0.0-alpha12 and use StringTemplate.

For Cpp, I add a new CppGenerator and bind new methods and attributes to particular types. The cppGenerator will use cpp/proto.stg. These works are very similar to current JavaGenerator. I will try to use ST extension in the future.

My company is using an internal custom style of cpp codes, which are quite different from the standard pb's.

**Comment by kshchepanovskyi** [comment]
Just implemented a foundation for ST extensions. Embedded Java generator now uses this mechanism, so technically it is possible to implement generator for any possible output format.

For maven, it works in a following way:

1. Set execution goal to `st4`.
2. Set two parameters: `template` - location of the root ST4 template, and `extensions` - name of the class that provides additional (calculated) properties to existing objects.

[Sample](https://github.com/protostuff/protostuff-compiler/blob/master/protostuff-it/pom.xml#L32):

```xml
<plugin>
	<groupId>io.protostuff</groupId>
	<artifactId>protostuff-maven-plugin</artifactId>
	<version>protostuff-compiler-2.0.0-alpha17</version>
	<executions>
		<execution>
			<id>generate-custom-java-sources</id>
			<phase>generate-sources</phase>
			<goals>
				<goal>st4</goal>
			</goals>
			<configuration>
				<template>io/protostuff/it/extension.stg</template>
				<extensions>io.protostuff.it.CustomExtensionProvider</extensions>
			</configuration>
		</execution>		
	</executions>
</plugin>
```

Note: extensions provider class should be compiled before plugin is invoked, it means it cannot be in the same maven module where we are generating sources. In the `protostuff-it` module it works because `io.protostuff.it.CustomExtensionProvider` is used in `generate-test-sources` phase which is executed after `compile` phase.

More documentation and some examples will be available later.

**Comment by kshchepanovskyi** [comment]
Also, you might find useful extension provider for Java (as example): https://github.com/protostuff/protostuff-compiler/blob/master/protostuff-generator/src/main/java/io/protostuff/generator/java/JavaExtensionProvider.java

This way you can follow strict model-view separation principle, so that template code will be as simple as possible, and all calculations will be in Java.
