### ISSUE TITLE
unknown option: json_name

### ISSUE THREAD

**Issue by Luke1410** [protostuff/protostuff-compiler#80]
Hi, 

when adding the json_name option to a proto file (see https://developers.google.com/protocol-buffers/docs/proto3 -> JSON Mapping -> notes on 'message' in the table), we are getting the following parser exception using protostuff-compiler 2.2.27:

io.protostuff.compiler.parser.ParserException: Unknown option: 'json_name' [test.proto:25]
        at io.protostuff.compiler.parser.OptionsPostProcessor.processStandardOptions(OptionsPostProcessor.java:145)
        [...]

Is this a known issue, or do we need to handle this case differently?

Regards,
Stefan

**Comment by kshchepanovskyi** [comment]
You can workaround it by adding the most recent google/protobuf/descriptor.proto to your project. There's one embedded with parser, but it might be outdated and do not have some options.

**Comment by kshchepanovskyi** [comment]
@Luke1410 please upgrade to the latest version, this option is supported there:
https://github.com/protostuff/protostuff-compiler/search?q=json_name

**Comment by StefanHISE** [comment]
> @Luke1410 please upgrade to the latest version, this option is supported there: https://github.com/protostuff/protostuff-compiler/search?q=json_name

We tried it with the latest available version (3.1.40) but it still triggers an error. I see that json_name is contained in the descriptor.proto file now as part of the FieldDescriptorProto, but still it does trigger an error for us when used within a proto file.

A colleague of mine came up with a workaround applying the following change to OptionsPostProcessor.java basically mimicking how the default keyword is handled (JSON_NAME = "json_name"):
![image](https://github.com/user-attachments/assets/579cc8c2-2307-45fd-8842-5b4d5d29f69c)

Are we up to something here and if so is there a change that this gets shipped with an update of protostuff?
